services:
  data_consuming:
    build: ./services/data_consuming
    depends_on:
      - kafka
      - mongodb
      - elasticsearch
    environment:
      KAFKA_TOPIC_NAME: file_metadata_topic
      KAFKA_GROUP_ID: data-consuming-group
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MONGODB_ATLAS_URI: mongodb://mongodb:27017
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
    restart: unless-stopped
  data_acceptance:
    build: ./services/data_acceptance
    depends_on:
      - kafka
    environment:
      KAFKA_TOPIC_NAME: file_metadata_topic
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: unless-stopped
    volumes:
      - /Users/mordechaywolff/Desktop/podcasts:/app/podcasts
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - discovery.type=single-node
    ports:
      - "9200:9200"
    restart: unless-stopped
