version: '3.8'
services:
  data_consuming:
    build: ./services/data_consuming
    depends_on:
      - kafka
      - mongodb
      - elasticsearch
    environment:
      KAFKA_TOPIC_NAME: file_metadata_topic
      KAFKA_GROUP_ID: data-consuming-group
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    restart: unless-stopped
  data_acceptance:
    build: ./services/data_acceptance
    depends_on:
      - kafka
    environment:
      KAFKA_TOPIC_NAME: file_metadata_topic
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    restart: unless-stopped
  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_PROCESS_ROLES: broker
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    restart: unless-stopped
